// js/utils/ids.js
// Booking IDs generated by this app are 'b' + creation-time-in-base36 (8
// chars) + 12 random chars = 21 chars total.
//
// DO NOT sort ids by plain string comparison. An earlier version did, on the
// assumption that every id shares that structure — it does not. Rows created
// before this scheme have ids like 'z5darnfgby11...' and 'yvgwqy26yjzt...'
// with no 'b' prefix, and lexicographically 'z' > 'y' > 'b' always. So every
// legacy row outranked every app-created row in a descending id sort,
// permanently, which is why "Recently Added" kept showing the same old rows
// at the top no matter what was booked. Use creationMs() below instead.

export function genId() {
  const ts = Date.now().toString(36);
  const rand = Array.from(crypto.getRandomValues(new Uint8Array(10)))
    .map(b => b.toString(36).padStart(2, '0')).join('').slice(0, 12);
  return 'b' + ts + rand;
}

// Creation time in epoch ms, decoded from the id. Returns -1 for any id not
// produced by genId() (legacy rows), since their creation time genuinely
// cannot be recovered from the id — callers should treat -1 as "oldest".
//
// The proper long-term fix is a real `created_at timestamptz default now()`
// column on public.bookings; this decoder exists because the id is currently
// the only creation-time signal available for existing data.
// Declared ABOVE creationMs() on purpose. These are `const`, so they sit in
// the temporal dead zone until this line executes — the function only worked
// because nothing calls it during module evaluation. Any future top-level
// call would have thrown "Cannot access before initialization".
const DAY_MS = 86400000;
// 2024-01-01. Nothing in this system predates it, so anything earlier is a
// coincidental decode rather than a real creation time.
const EARLIEST_PLAUSIBLE_MS = 1704067200000;

export function creationMs(id) {
  const head = String(id || '').slice(0, 9);
  if (!/^b[0-9a-z]{8}$/.test(head)) return -1;
  const ms = parseInt(head.slice(1), 36);
  if (!Number.isFinite(ms)) return -1;
  // The format check alone is NOT enough. Legacy rows also start with 'b'
  // followed by 8 base36 chars, but those chars are not a timestamp —
  // decoding them gives dates in 2055-2059 (verified against live data:
  // 'bzxt8e8j3...' -> 2059-03-31). Because 'bz' > 'bm' lexicographically AND
  // 2059 > 2026 numerically, those rows outranked every genuine booking in
  // "Recently Added" either way. A real creation time cannot be in the
  // future, so range-check it: that cleanly separates the two id families.
  if (ms > Date.now() + DAY_MS) return -1;   // decoded to the future -> not a timestamp
  if (ms < EARLIEST_PLAUSIBLE_MS) return -1; // decoded before this app existed
  return ms;
}

// Single definition of "when was this booking created", used by the initial
// sort in api/supabase-client.js and by the "Recently Added" sort in
// domain/filters-sort.js. Two slightly different rules is how those two
// disagreed in the first place.
//
// Prefers the created_at column (mapped to createdAtMs); falls back to
// decoding the id. created_at is NULLABLE by design — rows predating the
// column have no recoverable creation time — and is NOT fully backfilled, so
// the fallback is load-bearing, not defensive padding.
//
// Returns ms, or -1 for "unknown" so those rows sort as oldest. That is
// honest: their creation time genuinely is not recorded anywhere.
//
// Lives here rather than in api/ so that domain/ does not have to import from
// api/, which would invert the layering.
export function createdSortKey(b) {
  if (b.createdAtMs != null && !Number.isNaN(b.createdAtMs)) return b.createdAtMs;
  return creationMs(b.id);
}
